# fly.toml app configuration file generated for probe on 2024-06-10T01:59:49-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'probe'
primary_region = 'dfw'
kill_signal = 'SIGTERM'

[build]

[deploy]
release_command = '/app/bin/migrate'

[env]
PHX_HOST = 'probe.sh'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

# We can't forward a range of ports unfortunately, so we pick a few common
# ports to run the test from.

[[services]]
internal_port = 2053
protocol = "udp"
[[services.ports]]
port = 53

[[services]]
internal_port = 2080
protocol = "udp"
[[services.ports]]
port = 80

[[services]]
internal_port = 2123
protocol = "udp"
[[services.ports]]
port = 123

[[services]]
internal_port = 2161
protocol = "udp"
[[services.ports]]
port = 161

[[services]]
internal_port = 2443
protocol = "udp"
[[services.ports]]
port = 443

[[services]]
internal_port = 2500
protocol = "udp"
[[services.ports]]
port = 500

[[services]]
internal_port = 2514
protocol = "udp"
[[services.ports]]
port = 514

[[services]]
internal_port = 1701
protocol = "udp"
[[services.ports]]
port = 1701

[[services]]
internal_port = 51820
protocol = "udp"
[[services.ports]]
port = 51820

[[services]]
internal_port = 60000
protocol = "udp"
[[services.ports]]
port = 60000

[[vm]]
memory = '2gb'
cpu_kind = 'performance'
cpus = 1
