import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :probe, Probe.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :geolix,
  databases: [
    %{
      id: :city,
      adapter: Geolix.Adapter.MMDB2,
      source: "/usr/local/share/GeoIP/GeoLite2-City.mmdb"
    },
    %{
      id: :country,
      adapter: Geolix.Adapter.MMDB2,
      source: "/usr/local/share/GeoIP/GeoLite2-Country.mmdb"
    },
    %{
      id: :asn,
      adapter: Geolix.Adapter.MMDB2,
      source: "/usr/local/share/GeoIP/GeoLite2-ASN.mmdb"
    }
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
